url: 'https://yuanminglee.github.io'
baseurl: '/recipe-book'
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  recipes:
    output: true
