url: ""
baseurl: ""
title: "Recipe Book"

# Disabled for GitHub Pages compatibility - CSS is pre-processed
# plugins:
#   - jekyll-postcss

# postcss:
#   cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  recipes:
    output: true
