# wrangler.toml: Configuration for publishing the Cloudflare Worker

name = "recipe-worker"
account_id = "834eb2c847e8d6ac26c1f5a00e5c4603"  # Replace with your Cloudflare account ID
workers_dev = true
main = "worker.js"
compatibility_date = "2023-10-01"

[observability.logs]
enabled = true

[vars]
# Environment variables available to your worker
OPENAI_API_URL = "https://api.groq.com/openai/v1/chat/completions"
OPENAI_MODEL = "deepseek-r1-distill-llama-70b"
GITHUB_OWNER = "yuanminglee"   # Replace with your GitHub username or organization
GITHUB_REPO = "recipe-book"          # Replace with your repository name
GITHUB_BRANCH = "main"

# Note: Set sensitive keys using 'wrangler secret put', for example:
# wrangler secret put OPENAI_API_KEY
# wrangler secret put GITHUB_TOKEN 